/**:
  ros__parameters:
    grid_map_topic: /height_mapping/local/map

    grid_map_visualizations:
      - name: map_cloud
        type: point_cloud
        params:
          layer: elevation

      - name: mapping_region
        type: map_region
        params:
          color: "16777215"        # 0xFFFFFF en decimal
          line_width: "0.01"
