/**:
  ros__parameters:
    # --- I/O ---
    node.lidar_topic: /velodyne/points
    node.rgbd_topic:  /height_mapping/sensor_processor/points

    # --- Rates y flags ---
    node.pose_update_rate: 15.0
    node.map_publish_rate:  15.0
    node.remove_backward_points: true
    node.debug_mode: false

    # --- Frames ---
    frame_id.robot: base_link
    frame_id.map:   map

    # --- Config del mapper ---
    height_mapper.height_estimator:      StatMean    # StatMean | KalmanFilter | MovingAverage (lo que soporte tu nodo)
    height_mapper.frame_id:              map
    height_mapper.map_length_x:          10.0
    height_mapper.map_length_y:          10.0
    height_mapper.grid_resolution:       0.1
    height_mapper.min_height_threshold: -0.2
    height_mapper.max_height_threshold:  2.0
