/**:
  ros__parameters:
    # --- I/O ---
    node.input_cloud_topics:
      - /front/front_cam_depth_sensor/points
      - /left/left_cam_depth_sensor/points
      - /right/right_cam_depth_sensor/points
    node.outputcloud_topic: /height_mapping/sensor_processor/points

    # --- Rate & filtros ---
    node.cloud_publish_rate: 10.0
    node.downsample_resolution: 0.02     # [m/voxel]
    node.min_range_threshold: 0.3        # [m]
    node.max_range_threshold: 15.0       # [m]

    # --- Frames consumidos por frame_ids::loadFromConfig ---
    frame_id.robot: base_link
    frame_id.map:   map
